# Change these first
owner: stehled # Your GitHub organization or username, where this repository lives
repo: cr-upptime # The name of this repository

sites:
  - name: Cookierow Web
    url: https://www.cookierow.com
  - name: Cookierow API endpoint
    url: $CR_CR
  - name: Cookierow Policy
    url: $CR_POLICY

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cookierow.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.cookierow.com/assets/img/logo-cr.webp
  name: Cookierow
  introTitle: "**Cookierow** status page."
  introMessage: See information about the uptime of our service. Contact us in case of outage.
  navbar:
    - title: Status
      href: /
    - title: Cookierow
      href: https://www.cookierow.com
assignees:
  - stehled
  
i18n:
  footer: Status page for [Cookierow](https://www.cookierow.com).

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
